/**
 * Created by Steffen Naundorf on 01.06.2021.
 */

public without sharing class CommiteeOpportunityJunctionHandler extends TriggerHandlerExtension {
  public CommiteeOpportunityJunctionHandler() {
    super();
  }

  //public override void bulkBefore() { }

  public override void bulkAfter() {
  }

  //public override void beforeInsert(SObject obj) { addToLoopCount(); }

  //public override void beforeUpdate(SObject oldObj, SObject obj) { addToLoopCount(); }

  //public override void beforeDelete(SObject obj) { addToLoopCount();}

  //public override void afterInsert(SObject obj) { addToLoopCount(); }

  //public override void afterUpdate(SObject oldObj, SObject obj) { addToLoopCount(); }

  //public override void afterDelete(SObject obj) { addToLoopCount();}

  //public override void andFinally() { }
}
